name: Vercel Production Deployment


on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      customer:
        description: 'Customer to deploy'
        required: true
        type: choice
        options:
          - customer_1
          - customer_2

jobs:
  Deploy-Production-Specific-Customer:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     customer: [customer_1, customer_2] # no choice, all customers must be deployed together
    # defaults:
    #   run:
    #     working-directory: sites/${{ matrix.customer }}
    defaults:
      run:
        working-directory: sites/${{ github.event.inputs.customer }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
        continue-on-error: true

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}