name: Vercel Production Deployment - Static Sites

on:
  workflow_dispatch:
    inputs:
      customer:
        description: 'Customer to deploy'
        required: true
        type: choice
        options:
          - customer_1
          - customer_2
          - customer_3

jobs:
  Deploy-Production-Specific-Customer:
    name: Deploy Production for ${{ github.event.inputs.customer }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sites/${{ github.event.inputs.customer }}
    steps:
      - uses: actions/checkout@v2

      - name: Create Vercel Project ${{ github.event.inputs.customer }} (if not exists)
        run: |
          RESPONSE=$(curl -s \
            "https://api.vercel.com/v10/projects/${{ github.event.inputs.customer }}" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}")

          PROJECT_ID=$(echo $RESPONSE | jq -r '.id')

          if [ "$PROJECT_ID" = "null" ]; then
            echo "Project not found, creating..."
            RESPONSE=$(curl -s -X POST "https://api.vercel.com/v10/projects" \
              -H "Authorization: Bearer ${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{"name": "${{ github.event.inputs.customer }}"}')
            echo $RESPONSE
            PROJECT_ID=$(echo $RESPONSE | jq -r '.id')
          else
            echo "Project already exists, skipping creation."
          fi

          echo "VERCEL_PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      ## Not required for static sites

      ## fetch environment variables and build the project locally before deploying to Vercel, as this can help ensure that the deployment process is more efficient and less prone to issues related to missing environment variables or build errors on the Vercel platform.
      # - name: Pull Vercel Environment Information
      #   run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
      #   env:
      #     VERCEL_PROJECT_ID: ${{ env.VERCEL_PROJECT_ID }}
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      ## build the project locally to ensure that all necessary environment variables are available and to catch any build errors before deploying to Vercel. This can help improve the reliability of the deployment process and reduce the likelihood of issues related to missing environment variables or build errors on the Vercel platform.
      # - name: Build Project Artifacts
      #   run: vercel build --prod --token=${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
      #   env:
      #     VERCEL_PROJECT_ID: ${{ env.VERCEL_PROJECT_ID }}
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      # - name: Deploy Project Artifacts to Vercel
      #   run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
      #   env:
      #     VERCEL_PROJECT_ID: ${{ env.VERCEL_PROJECT_ID }}
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

            
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ env.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}